name: Deploy to FTP

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2  # Use the desired Node.js version

      - name: Install dependencies and build Next.js app
        run: |
          npm install  # Install project dependencies
          touch .env.local
          echo LOCAL_URL=https://zarinadressing.com >> .env.local
          echo NEXT_PUBLIC_LOCAL_URL=https://zarinadressing.com >> .env.local
          echo API_URL=https://zarinadressing.com/api/public/api >> .env.local
          echo NEXT_PUBLIC_API_URL="https://zarinadressing.com/api/public/api" >> .env.local
          echo NEXT_PUBLIC_URL="https://zarinadressing.com/api/public"
          # echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env.local
          # echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.local
          npm run build  # Build Next.js app

      - name: Deploy via FTP
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ftp.kolomabeledrc.com # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          port: 21 # optional, default is: 21
          user: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          remoteDir: /zarinadressing.com/zarina/ # optional, remote path of your FTP server
          localDir: . # optional, local path, default is: dist
          # SFTP credentials
          # host: sftp.kolomabeledrc.com
          # port: 21
          # user: ${{ secrets.FTP_USERNAME }}
          # pass: ${{ secrets.FTP_PASSWORD }}
          # lftp settings
          # onlyNewer: true
          # settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          # localDir: '.'
          # remoteDir: /zarinadressing.com/zarina/
          # reverse: true
          # ignoreFile: '.lftp_ignore'
          # options: '--verbose'
        
